tweetmodel/urls.py
from django.urls import path

from .views import CreateTweet, DeleteTweet

app_name = "tweets"

urlpatterns = [
    path('', CreateTweet.as_view(), name='tweet'),
    path('<int:pk>/delete/', DeleteTweet.as_view(), name='deletetweet'),
]

twitterclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tweet/', include('tweetmodel.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import CreateUserView, UserHomePage, CustomLogin, UpdateUser, UpdateProfilePicture

app_name = 'users'

urlpatterns = [
    path('signup/', CreateUserView.as_view(), name="signup"),
    path('login/', CustomLogin.as_view(), name="login"),
    path('<slug:username>/', UserHomePage.as_view(), name="userpage"),
    path('<slug:username>/update/', UpdateUser.as_view(), name="updateuserpage"),
    path('<int:pk>/updatepicture/', UpdateProfilePicture.as_view(), name='updateprofilepicture'),
]

#cache_page(60*15)

tweetmodel/models.py
from django.db import models

from django.contrib.auth import get_user_model

# Create your models here.


class TweetModelBase(models.Model):

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    likes = models.PositiveIntegerField(default=0)

    date = models.DateTimeField(auto_now=True)

    class Meta:

        abstract = True


class TweetModel(TweetModelBase):

    tweet = models.CharField(max_length=140, default='')

    def __str__(self):

        return self.user.email.split('@')[0] + ': ' + self.tweet[0:9]


class TweetPictureModel(TweetModelBase):

    tweet = models.CharField(max_length=70, default='')

    picture = models.ImageField(upload_to='media/', default='media/kitten.jpg')


class TweetVideoModel(TweetModelBase):
    pass

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings
from .renameandupload import path_and_rename


class CustomBaseUserManager(BaseUserManager):

    def create_user(self, age, email, username, password=None):
        if not email:
            raise ValueError("You need an email address")

        user = self.model(
            email=self.normalize_email(email),
            age=age,
            username=username,
        )

        user.set_password(password)

        user.save(using=self._db)

        return user

    def create_superuser(self, age, email, username, password):
        user = self.create_user(
            age,
            email,
            username,
            password
        )

        user.is_admin = True
        user.save(using=self._db)

        return user


class CustomUser(AbstractUser):

    age = models.PositiveIntegerField()
    bio = models.CharField(max_length=140)
    email = models.EmailField(unique=True, blank=False, max_length=254, verbose_name='email address')

    objects = CustomBaseUserManager

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['age', 'username']

    def __str__(self):
        return self.email


class FollowFollowerModel(models.Model):

    pass


class UserPictureModel(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='users')

    profilepicture = models.ImageField(upload_to=path_and_rename)

    def __str__(self):

        return self.user.username + '\' profile picture'

tweetmodel/forms.py
from django.forms import ModelForm

from .models import TweetModel


class TweetForm(ModelForm):

    class Meta:

        model = TweetModel

        fields = ['tweet']

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):

        model = CustomUser

        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'age', 'bio',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:

        model = CustomUser

        fields = ('first_name', 'last_name', 'email', 'bio', 'age',)

tweetmodel/views.py
from django.core.exceptions import PermissionDenied
from django.views.generic import CreateView, DeleteView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from .models import TweetModel
from .forms import TweetForm
# Create your views here.


class CreateTweet(LoginRequiredMixin, CreateView):

    #form_class = TweetForm

    model = TweetModel

    template_name = 'tweet.html'

    fields = ('tweet',)

    def get_success_url(self):

        return reverse('users:userpage', args=[self.request.user.username], )

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DeleteTweet(LoginRequiredMixin, DeleteView):

    model = TweetModel

    template_name = 'delete_tweet.html'

    login_url = 'users:login'

    def get_success_url(self):

        return reverse('users:userpage', args=[self.request.user.username], )

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()

        if obj.user != self.request.user:
            raise PermissionDenied

        return super().delete(request, *args, **kwargs)


class ViewTweet(DetailView):

    model = TweetModel

    context_object_name = 'tweet'


class ViewTweets(ListView):

    model = TweetModel

    context_object_name = 'tweets'

user/views.py
from django.shortcuts import render

from django.views.generic import CreateView, DetailView, UpdateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
# Create your views here.

from .forms import CustomUserCreationForm
from .models import CustomUser, UserPictureModel
from tweetmodel.models import TweetModel


class CreateUserView(CreateView):

    form_class = CustomUserCreationForm

    success_url = reverse_lazy('home')

    template_name = 'registration/signup.html'


class UserHomePage(LoginRequiredMixin, DetailView):

    template_name = 'userpage.html'

    model = CustomUser

    context_object_name = "user"

    slug_field = 'username'

    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):

        context = super(UserHomePage, self).get_context_data(**kwargs)
        context['tweets'] = TweetModel.objects.all()
        context['userpicture'] = UserPictureModel.objects.get(user=self.request.user)
        return context


class UpdateUser(LoginRequiredMixin, UpdateView):

    model = get_user_model()

    fields = ('bio', )

    template_name = 'edituserpage.html'

    slug_field = 'username'

    slug_url_kwarg = 'username'

    def get_success_url(self):

        return reverse('users:userpage', args=[self.request.user.username], )

    def get_context_data(self, **kwargs):

        context = super(UpdateUser, self).get_context_data(**kwargs)

        return context


class UpdateProfilePicture(LoginRequiredMixin, UpdateView):

    model = UserPictureModel

    fields = ('profilepicture',)

    template_name = 'updateprofilepicture.html'

    def get_success_url(self):
        return reverse('users:userpage', args=[self.request.user.username], )


class CustomLogin(LoginView):

    def get_success_url(self):

        url = self.get_redirect_url()

        return url or reverse('users:userpage', args=[self.request.user.username], )

templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %} Twitter Clone {% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{%  static 'homepage.css' %}" >
    {% block css %} {% endblock css %}
</head>
<body>

    <main>
        {% block content %}
        {% endblock content %}
    </main>

    {% block javascript %}{% endblock javascript %}
</body>
</html>

templates/edituserpage.html
{%  extends 'base.html' %}

{% block content %}

    <div>
    <h1>Update your info</h1>

    <form method="post" action="">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update my profile</button>
    </form>
    </div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div id="header">
        <ul>
            {% if user.is_authenticated %}
                <a href="{%  url 'logout' %}">logout</a>
            {% else %}
                <li>
                    <a href="#">signup</a>
                </li>
                <li>
                    <a href="{%  url 'users:login' %}">login</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <!--<div>-->
        <img id="landingpageimage"  src="http://placekitten.com/600/300">
    <!--</div>-->

    <div id="landingpagetext">
        <div id="landingpagetext-1">
            A clone of most of the basic features of Twitter. It's not exact but I'm trying to get close.
        </div>

        <div id="landingpagetext-2">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur cursus ipsum lorem, quis elementum dolor
                viverra ut. Sed porttitor, justo a elementum ultricies, augue lectus laoreet metus, et imperdiet ante lacus a nunc.
                Morbi tellus enim, mattis pharetra lacus ac, facilisis vehicula nunc. Nam accumsan lacinia augue, eu placerat arcu.
            </p>
        </div>

        <div id="landingpagetext-3">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur cursus ipsum lorem, quis elementum dolor
                viverra ut. Sed porttitor, justo a elementum ultricies, augue lectus laoreet metus, et imperdiet ante lacus a nunc.
                Morbi tellus enim, mattis pharetra lacus ac, facilisis vehicula nunc. Nam accumsan lacinia augue, eu placerat arcu.
            </p>
        </div>
    </div>

    <div>
        <button>Sign up!</button>
    </div>
{% endblock content %}

templates/tweet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Tweet!</button>
    </form>
</body>
</html>

templates/updateprofilepicture.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>New Picture</h2>
    <form method="post" action="">
        {% csrf_token%}
        {{ form.as_p }}
        <button type="submit">New Picture</button>
    </form>
</div>
{% endblock content %}

templates/userpage.html
{% extends 'base.html' %}

{%  block title %}
    User - {{ user.username }}
{%  endblock title %}

{%  block content %}

    <div id="header">
        <ul>
                <a href="{%  url 'logout' %}">logout</a>
        </ul>
    </div>

    <div id="usercontainer">
        <div id="user">
            <ul>
                <li>
                    <a href="{% url 'users:updateprofilepicture' userpicture.pk %}">
                        {%  if userpicture.user != null %}
                        <img src="{{ userpicture.profilepicture.url }}" />
                        {% else %}
                        <img src="https://placekitten.com/200/300" />
                        {% endif %}
                    </a>
                </li>
                <li>
                    {{ user.username }}
                </li>
                <li>
                    {{ user.date_joined|date:"F, Y" }}
                </li>
                <li>
                    {{ user.bio }}
                </li>
                <li>
                    <a href="{% url 'users:updateuserpage' user.username %}">update my profile</a>
                </li>
            </ul>


            <p>Follow Feature to come.</p>
        </div>

        <div id="tweets">
            <a href="{% url 'tweets:tweet' %}">Tweet!</a>
            {%  for tweet in tweets %}
                <div class="tweet">
                    <p class="tweet-top">
                        {{ user.first_name }} {{ user.last_name }}
                        <a href="#">@{{ user.username }}</a>
                        {{ tweet.date|date:"M, j, Y" }}
                        <span><a href="{% url 'tweets:deletetweet' tweet.pk %}">delete</a></span>
                    </p>
                    <p class="tweet-bottom">{{ tweet.tweet }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{%  endblock content %}